export type Role = 'ADMIN' | 'WAREHOUSE_MANAGER' | 'ACCOUNTANT' | 'SALES' | 'READ_ONLY';

export const PERMISSIONS = {
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  VIEW_CHALLANS: 'VIEW_CHALLANS',
  CREATE_CHALLANS: 'CREATE_CHALLANS',
  APPROVE_CHALLANS: 'APPROVE_CHALLANS',
  DISPATCH_CHALLANS: 'DISPATCH_CHALLANS',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  VIEW_AUDIT: 'VIEW_AUDIT',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
} as const;

export type Permission = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS),
  WAREHOUSE_MANAGER: [
    'VIEW_INVENTORY', 'MANAGE_INVENTORY', 
    'VIEW_CHALLANS', 'CREATE_CHALLANS', 'DISPATCH_CHALLANS',
  ],
  ACCOUNTANT: [
    'VIEW_INVENTORY', 'VIEW_CHALLANS', 'APPROVE_CHALLANS',
    'VIEW_CUSTOMERS', 'VIEW_AUDIT'
  ],
  SALES: [
    'VIEW_INVENTORY', 'VIEW_CHALLANS', 'CREATE_CHALLANS',
    'VIEW_CUSTOMERS', 'MANAGE_CUSTOMERS'
  ],
  READ_ONLY: [
    'VIEW_INVENTORY', 'VIEW_CHALLANS', 'VIEW_CUSTOMERS'
  ]
};

export function hasPermission(userRole: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[userRole]?.includes(permission) ?? false;
}
