import { createBrowserClient as createSSRBrowserClient } from "@supabase/ssr";
import { supabaseConfig } from "@/config";
import type { Database } from "@/types"; // This will be generated by Supabase CLI

export const createBrowserClient = () => {
  return createSSRBrowserClient<Database>(
    supabaseConfig.url,
    supabaseConfig.anonKey
  );
};
